import {processSearch} from '../../../lib/jobs';
import {db,rows,setting,saveSetting,secret,runtime} from '../../../lib/data';
import {identity,limit} from '../../../lib/auth';
import {digest,encrypt,passwordHash,random,safeEqual,validMeet} from '../../../lib/security';
import {z} from 'zod';
export const dynamic='force-dynamic';
const json=(data:unknown,status=200,headers:Record<string,string>={})=>Response.json(data,{status,headers:{'Cache-Control':'no-store',...headers}});
const now=()=>new Date().toISOString();
const field=z.string().trim().min(1).max(200);
const seminarSchema=z.object({title:field,description:z.string().max(10000),start:z.string().datetime(),duration:z.coerce.number().int().min(15).max(1440),price:z.coerce.number().int().min(0).max(100000000),capacity:z.coerce.number().int().min(1).max(10000),format:z.enum(['online','in_person']),location:z.string().max(200).default(''),meet_url:z.string().max(200).default(''),published:z.boolean().default(false)});
async function listSeminars(admin:boolean,userId?:string){if(admin)return rows('SELECT s.*,(SELECT count(*) FROM enrollments e WHERE e.seminar_id=s.id AND status=\'paid\') AS enrolled FROM seminars s ORDER BY start');return rows("SELECT s.id,s.title,s.description,s.start,s.duration,s.price,s.capacity,s.format,s.location,e.status AS enrollment_status FROM seminars s LEFT JOIN enrollments e ON e.seminar_id=s.id AND e.user_id=? WHERE s.published=1 ORDER BY s.start",userId||'');}
export async function GET(req:Request){try{const user=await identity(req);const action=new URL(req.url).searchParams.get('action')||'state';if(action==='join'){const id=new URL(req.url).searchParams.get('id');if(!user)return json({error:'Giriş yapın.'},401);if(user.must_change)return json({error:'Önce şifrenizi değiştirin.'},403);const s=await db().prepare('SELECT * FROM seminars WHERE id=?').bind(id).first<any>();if(!s||s.format!=='online')return json({error:'Online eğitim bulunamadı.'},404);if(user.role!=='admin'){const e=await db().prepare("SELECT id FROM enrollments WHERE user_id=? AND seminar_id=? AND status='paid'").bind(user.id,id).first();if(!e)return json({error:'Bu eğitime erişiminiz yok.'},403);const start=Date.parse(s.start);if(Date.now()<start-1800000||Date.now()>start+s.duration*60000)return json({error:'Katılım, eğitimden 30 dakika önce açılır.'},403)}if(!validMeet(s.meet_url))return json({error:'Eğitmen henüz Meet bağlantısını eklemedi.'},409);return new Response(null,{status:302,headers:{Location:s.meet_url,'Cache-Control':'no-store','Referrer-Policy':'no-referrer'}})}
if(action==='place'){if(user?.role!=='admin')return json({error:'Yetkiniz yok.'},403);const key=await secret('google_places_key');if(!key)return json({error:'Google Places bağlantısını tamamlayın.'},409);const id=new URL(req.url).searchParams.get('id')||'';if(!/^[\w-]{5,200}$/.test(id))return json({error:'Geçersiz yer.'},400);const r=await fetch('https://places.googleapis.com/v1/places/'+encodeURIComponent(id),{headers:{'X-Goog-Api-Key':key,'X-Goog-FieldMask':'id,displayName,formattedAddress,nationalPhoneNumber,websiteUri,googleMapsUri,attributions'},signal:AbortSignal.timeout(20000)});if(!r.ok)return json({error:'Google yer ayrıntılarını getiremedi.'},502);return json(await r.json())}
const seminars=await listSeminars(user?.role==='admin',user?.id as string);if(user?.role!=='admin'||user.must_change)return json({user,seminars,setup:!await setting('owner')&&!!req.headers.get('oai-authenticated-user-id')});const [contacts,participants,campaigns,deliveries,jobs,places]=await Promise.all([rows('SELECT * FROM contacts ORDER BY created DESC LIMIT 1000'),rows('SELECT u.id,u.username,u.name,u.email,u.phone,e.id AS enrollment_id,e.status,s.title,s.id AS seminar_id FROM users u LEFT JOIN enrollments e ON e.user_id=u.id LEFT JOIN seminars s ON s.id=e.seminar_id WHERE u.role=\'participant\' ORDER BY u.created DESC LIMIT 1000'),rows('SELECT * FROM campaigns ORDER BY created DESC'),rows('SELECT * FROM deliveries ORDER BY created DESC LIMIT 1000'),rows('SELECT * FROM jobs ORDER BY created DESC LIMIT 20'),rows('SELECT * FROM places ORDER BY created DESC LIMIT 200')]);const integrations={google:!!await setting('google_places_key'),whatsapp:!!await setting('wa_token')&&!!await setting('wa_phone_id'),meet:!!await setting('google_refresh_token'),instagram:await setting('instagram'),facebook:await setting('facebook')};return json({user,seminars,contacts,participants,campaigns,deliveries,jobs,places,integrations});}catch{return json({error:'Veriler yüklenemedi. Lütfen yeniden deneyin.'},500)}}
export async function POST(req:Request){try{if(req.headers.get('origin')!==new URL(req.url).origin)return json({error:'Geçersiz istek kaynağı.'},403);if(!req.headers.get('content-type')?.includes('application/json'))return json({error:'JSON gerekli.'},415);const raw=await req.text();if(raw.length>50000)return json({error:'İstek çok büyük.'},413);const p=JSON.parse(raw);const a=p.action;const user=await identity(req);
if(a==='setup'){const platform=req.headers.get('oai-authenticated-user-id');if(!platform||runtime().ALLOW_OWNER_SETUP!=='true')return json({error:'Kurulum yalnızca özel site sahibi tarafından yapılabilir.'},403);await db().prepare("INSERT OR IGNORE INTO settings(key,value) VALUES('owner',?)").bind(platform).run();if(await setting('owner')!==platform)return json({error:'Yönetici zaten atanmış.'},403);return json({ok:true})}
if(a==='login'){await limit('login:'+await digest(req.headers.get('cf-connecting-ip')||'unknown'));const name=z.string().min(1).max(100).parse(p.username).toLowerCase();const pass=z.string().min(1).max(200).parse(p.password);const u=await db().prepare('SELECT * FROM users WHERE username=?').bind(name).first<any>();const hash=await passwordHash(pass,u?.salt||'nonexistent-account-salt');if(!u||!safeEqual(hash,u.password))return json({error:'Kullanıcı adı veya şifre hatalı.'},401);const token=random();await db().prepare('INSERT INTO sessions(token,user_id,expires) VALUES(?,?,?)').bind(await digest(token),u.id,Date.now()+86400000).run();return json({ok:true},200,{'Set-Cookie':`hd_session=${token}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=86400`})}
if(a==='register'){await limit('register:'+await digest(req.headers.get('cf-connecting-ip')||'unknown'),5);const v=z.object({name:field,email:z.string().email(),phone:z.string().regex(/^\+90\d{10}$/),seminar_id:z.string().uuid(),consent:z.literal(true)}).parse(p);const seminar=await db().prepare('SELECT id,capacity,start FROM seminars WHERE id=? AND published=1').bind(v.seminar_id).first<any>();if(!seminar||Date.parse(seminar.start)<Date.now())throw new Error('Bu eğitim kayıt almıyor.');const id=crypto.randomUUID(),username='hekim'+random().slice(0,10),password=random().slice(0,18),salt=random();await db().batch([db().prepare('INSERT INTO users(id,username,name,email,phone,password,salt,created) VALUES(?,?,?,?,?,?,?,?)').bind(id,username,v.name,v.email,v.phone,await passwordHash(password,salt),salt,now()),db().prepare('INSERT INTO enrollments(id,user_id,seminar_id,status,created) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),id,v.seminar_id,'pending',now())]);return json({ok:true,credentials:{username,password}})}
if(a==='logout'){const t=req.headers.get('cookie')?.match(/(?:^|;\s*)hd_session=([^;]+)/)?.[1];if(t)await db().prepare('DELETE FROM sessions WHERE token=?').bind(await digest(t)).run();return json({ok:true},200,{'Set-Cookie':'hd_session=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0'})}
if(!user)return json({error:'Giriş yapmanız gerekiyor.'},401);
if(a==='password'){const pass=z.string().min(12).max(200).parse(p.password);const salt=random();await db().batch([db().prepare('UPDATE users SET password=?,salt=?,must_change=0 WHERE id=?').bind(await passwordHash(pass,salt),salt,user.id),db().prepare('DELETE FROM sessions WHERE user_id=?').bind(user.id)]);return json({ok:true,relogin:true},200,{'Set-Cookie':'hd_session=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0'})}
if(user.must_change)return json({error:'Önce şifrenizi değiştirin.'},403);
if(user.role!=='admin')return json({error:'Bu işlem için yönetici yetkisi gerekiyor.'},403);
if(a==='seminar'){const s=seminarSchema.parse(p);if(s.meet_url&&!validMeet(s.meet_url))throw new Error('Geçerli bir Google Meet bağlantısı girin.');if(s.format==='in_person'&&!s.location)throw new Error('Eğitim yeri gerekli.');const id=p.id?z.string().uuid().parse(p.id):crypto.randomUUID();await db().prepare('INSERT INTO seminars(id,title,description,start,duration,price,capacity,format,location,meet_url,published,created) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET title=excluded.title,description=excluded.description,start=excluded.start,duration=excluded.duration,price=excluded.price,capacity=excluded.capacity,format=excluded.format,location=excluded.location,meet_url=excluded.meet_url,published=excluded.published').bind(id,s.title,s.description,s.start,s.duration,s.price,s.capacity,s.format,s.location,s.meet_url,s.published?1:0,now()).run();return json({ok:true,id})}
if(a==='administrator'){const v=z.object({name:field,email:z.string().email()}).parse(p);const id=crypto.randomUUID(),username='yonetici'+random().slice(0,8),password=random().slice(0,18),salt=random();await db().prepare('INSERT INTO users(id,username,name,email,role,password,salt,created) VALUES(?,?,?,?,?,?,?,?)').bind(id,username,v.name,v.email,'admin',await passwordHash(password,salt),salt,now()).run();return json({ok:true,credentials:{username,password}})}
if(a==='participant'){const v=z.object({name:field,email:z.string().email(),phone:z.string().max(30).default(''),seminar_id:z.string().uuid()}).parse(p);const seminar=await db().prepare('SELECT id FROM seminars WHERE id=?').bind(v.seminar_id).first();if(!seminar)throw new Error('Önce eğitim oluşturun.');const id=crypto.randomUUID(),username='hekim'+random().slice(0,10),password=random().slice(0,18),salt=random();await db().batch([db().prepare('INSERT INTO users(id,username,name,email,phone,password,salt,created) VALUES(?,?,?,?,?,?,?,?)').bind(id,username,v.name,v.email,v.phone,await passwordHash(password,salt),salt,now()),db().prepare('INSERT INTO enrollments(id,user_id,seminar_id,status,created) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),id,v.seminar_id,'pending',now())]);return json({ok:true,credentials:{username,password}})}
if(a==='payment'){const id=z.string().uuid().parse(p.id);const status=z.enum(['paid','pending','cancelled']).parse(p.status);const result=await db().prepare("UPDATE enrollments SET status=? WHERE id=? AND (? != 'paid' OR status='paid' OR (SELECT count(*) FROM enrollments x WHERE x.seminar_id=enrollments.seminar_id AND x.status='paid') < (SELECT capacity FROM seminars WHERE id=enrollments.seminar_id)) RETURNING id").bind(status,id,status).first();if(!result)throw new Error('Kayıt bulunamadı veya kontenjan dolu.');return json({ok:true})}
if(a==='reset_password'){const id=z.string().uuid().parse(p.id);const password=random().slice(0,18),salt=random();const u=await db().prepare('SELECT username FROM users WHERE id=?').bind(id).first<any>();if(!u)throw new Error('Katılımcı bulunamadı.');await db().batch([db().prepare('UPDATE users SET password=?,salt=?,must_change=1 WHERE id=?').bind(await passwordHash(password,salt),salt,id),db().prepare('DELETE FROM sessions WHERE user_id=?').bind(id)]);return json({ok:true,credentials:{username:u.username,password}})}
if(a==='settings'){const allowed=['google_places_key','wa_token','wa_phone_id','google_client_id','google_client_secret','google_refresh_token'];for(const k of allowed){if(typeof p[k]==='string'&&p[k].trim()){if(p[k].length>10000)throw new Error('Anahtar çok uzun.');await saveSetting(k,await encrypt(p[k].trim(),runtime().APP_ENCRYPTION_KEY))}}for(const k of ['instagram','facebook'])if(typeof p[k]==='string'){if(p[k]){const u=new URL(p[k]);if(u.protocol!=='https:'||!['instagram.com','www.instagram.com','facebook.com','www.facebook.com'].includes(u.hostname))throw new Error('Geçerli bir sosyal medya bağlantısı girin.')}await saveSetting(k,p[k])}return json({ok:true})}
if(a==='contact'){const v=z.object({name:field,city:field,specialty:field,phone:z.string().regex(/^\+90\d{10}$/,'Telefon +90 ile başlayan 12 rakam olmalı.'),email:z.union([z.literal(''),z.string().email()]).default(''),consent:z.boolean(),consent_source:z.string().max(500),notes:z.string().max(2000).default('')}).parse(p);if(v.consent&&!v.consent_source.trim())throw new Error('İletişim izninin kaynağını ve tarihini yazın.');await db().prepare('INSERT INTO contacts(id,name,city,specialty,phone,email,consent,consent_source,notes,created) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),v.name,v.city,v.specialty,v.phone,v.email,v.consent?1:0,v.consent_source,v.notes,now()).run();return json({ok:true})}
if(a==='contact_status'){const id=z.string().uuid().parse(p.id);const status=z.enum(['new','interested','not_interested','opted_out']).parse(p.status);await db().prepare("UPDATE contacts SET status=?,consent=CASE WHEN ?='opted_out' THEN 0 ELSE consent END WHERE id=?").bind(status,status,id).run();return json({ok:true})}
if(a==='search'){const cities=z.array(field).min(1).max(81).parse(p.cities);const specialties=z.array(field).min(1).max(8).parse(p.specialties);if(!await secret('google_places_key'))throw new Error('Önce Ayarlar bölümünden Google Places API anahtarını ekleyin.');const queries=cities.flatMap(city=>specialties.map(specialty=>({city,specialty})));await db().prepare('INSERT INTO jobs(id,queries,created) VALUES(?,?,?)').bind(crypto.randomUUID(),JSON.stringify(queries),now()).run();return json({ok:true})}
if(a==='search_step')return json(await processSearch(z.string().uuid().parse(p.id)));
if(a==='retry_search'){await db().prepare("UPDATE jobs SET status='pending',lease=0,error='' WHERE id=? AND status='failed'").bind(z.string().uuid().parse(p.id)).run();return json({ok:true})}
if(a==='campaign'){const v=z.object({title:field,seminar_id:z.string().uuid(),template:z.string().regex(/^[a-z0-9_]{1,100}$/),language:z.string().regex(/^[a-z]{2}(_[A-Z]{2})?$/)}).parse(p);await db().prepare('INSERT INTO campaigns(id,title,seminar_id,template,language,created) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),v.title,v.seminar_id,v.template,v.language,now()).run();return json({ok:true})}
if(a==='send'){const c=await db().prepare('SELECT c.*,s.published FROM campaigns c JOIN seminars s ON s.id=c.seminar_id WHERE c.id=?').bind(z.string().uuid().parse(p.id)).first<any>();if(!c||!c.published)throw new Error('Yayımlanmış bir eğitim seçin.');const token=await secret('wa_token'),phoneId=await secret('wa_phone_id');if(!token||!/^\d+$/.test(phoneId))throw new Error('WhatsApp Business bağlantısını tamamlayın.');const contacts=await rows("SELECT c.* FROM contacts c WHERE c.consent=1 AND c.status!='opted_out' AND NOT EXISTS(SELECT 1 FROM deliveries d WHERE d.contact_id=c.id AND d.campaign_id=?) LIMIT 10",c.id);let sent=0;for(const contact of contacts as any[]){const delivery=crypto.randomUUID();const claimed=await db().prepare("INSERT OR IGNORE INTO deliveries(id,campaign_id,contact_id,status,created) VALUES(?,?,?,'sending',?)").bind(delivery,c.id,contact.id,now()).run();if(!claimed.meta.changes)continue;try{const r=await fetch(`https://graph.facebook.com/v23.0/${phoneId}/messages`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({messaging_product:'whatsapp',to:contact.phone.replace('+',''),type:'template',template:{name:c.template,language:{code:c.language}}}),signal:AbortSignal.timeout(20000)});const data:any=await r.json();if(!r.ok){await db().prepare("UPDATE deliveries SET status='failed',error=? WHERE id=?").bind(`Meta hata kodu: ${data.error?.code||r.status}`,delivery).run();continue}await db().prepare("UPDATE deliveries SET status='accepted',provider_id=? WHERE id=?").bind(data.messages?.[0]?.id||'',delivery).run();sent++}catch{await db().prepare("UPDATE deliveries SET status='unknown',error='Yanıt alınamadı. Tekrar göndermeden önce Meta kayıtlarını kontrol edin.' WHERE id=?").bind(delivery).run()}}return json({ok:true,message:`${sent} mesaj WhatsApp tarafından kabul edildi. Bu, teslim veya okunma onayı değildir.`})}
if(a==='meet_create'){const id=z.string().uuid().parse(p.id);const s=await db().prepare('SELECT id,meet_url FROM seminars WHERE id=?').bind(id).first<any>();if(!s)throw new Error('Eğitim bulunamadı.');if(s.meet_url)throw new Error('Bu eğitimde zaten Meet bağlantısı var.');const client=await secret('google_client_id'),cs=await secret('google_client_secret'),refresh=await secret('google_refresh_token');if(!client||!cs||!refresh)throw new Error('Google hesabı bağlantısı eksik. Mevcut Meet bağlantısını eğitim formuna ekleyebilirsiniz.');const t=await fetch('https://oauth2.googleapis.com/token',{method:'POST',body:new URLSearchParams({client_id:client,client_secret:cs,refresh_token:refresh,grant_type:'refresh_token'}),signal:AbortSignal.timeout(15000)});if(!t.ok)throw new Error('Google hesap yetkisi yenilenemedi.');const auth:any=await t.json();const r=await fetch('https://meet.googleapis.com/v2/spaces',{method:'POST',headers:{Authorization:`Bearer ${auth.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({config:{accessType:'RESTRICTED'}}),signal:AbortSignal.timeout(15000)});if(!r.ok)throw new Error('Google Meet toplantısı oluşturulamadı.');const room:any=await r.json();if(!validMeet(room.meetingUri))throw new Error('Google geçerli bir toplantı bağlantısı döndürmedi.');await db().prepare('UPDATE seminars SET meet_url=? WHERE id=?').bind(room.meetingUri,id).run();return json({ok:true})}
return json({error:'İşlem bulunamadı.'},400);
}catch(e){if(e instanceof z.ZodError)return json({error:e.issues[0]?.message||'Alanları kontrol edin.'},400);return json({error:e instanceof Error&&!/SQLITE|D1_|constraint|syntax/i.test(e.message)?e.message:'İşlem kaydedilemedi. Alanları kontrol edip yeniden deneyin.'},400)}}
